name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  CI_macOS:
    name: Run macOS Tests
    runs-on: macos-26
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_26.3.app

      - name: Run CI_macOS Scheme
        run: set -o pipefail && xcodebuild clean test -workspace ExpenseManagerApp/ExpenseManagerAppWorkspace.xcworkspace -scheme CI_macOS CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination 'platform=macOS' | xcpretty

  CI_iOS:
    name: Run iOS Tests
    runs-on: macos-26
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_26.3.app

      - name: Run CI_iOS Scheme
        run: set -o pipefail && xcodebuild clean test -workspace ExpenseManagerApp/ExpenseManagerAppWorkspace.xcworkspace -scheme CI_iOS CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' | xcpretty

